language: objective-c
osx_image: xcode611
before_install:
  - brew update
  - brew install carthage
  - scripts/keychain.sh
  - carthage bootstrap
  - gem instal xcpretty
script:
  - xcodebuild -project Conjure.xcodeproj -scheme Conjure clean test -sdk iphonesimulator
env:
  global:
    secure: HkCjOaOfEFi2vJlCGV4EZ5w1Nta8DKdMUwfbZ4FJKls31BpfCsmR2t6u0FoL3UYt3E/PajuW8Z9LP+y0BRD79ugTSKqnxVl3l/mNaU09F8DX8yI3J/xQ1O6JhV+hxOpUV20qcf69MrEqkRcnffeCjMm+1EIALK9fN7qO9qj9zG8=
