language: objective-c
osx_image: xcode611
before_install:
- brew update
- brew install carthage
- scripts/keychain.sh
- carthage bootstrap
- gem instal xcpretty
script:
- xcodebuild -project Conjure.xcodeproj -scheme Conjure clean test -sdk iphonesimulator
env:
  global:
  - secure: Tvgu9XRXgXRLC+XfVrru4D2WBh1XrB0YSQRyzr5HoPRPR9ohMOZaTfc2pK0AQblX3UrmuuzO3z0BqyZ8SiPvhZvKiG3iL/XWkZD22FxfsqCfV3l5YuKL6LjcY3ZH9tFwZ0VgDteX9se9MWBoYen0Zo35zwTWb1Dl44BnVdFXtmA=
